### ISSUE TITLE
Testing the Link Prediction Model

### ISSUE THREAD

**Issue by barkincavdaroglu** [ajmcquilkin/meshtastic-network-management-client#152]
Until we have realistic data in sufficient amount, we can use the following datasets to train and test the performance of our model:

(1) **CONTACT** (http://konect.cc/fles/download.tsv.contact.tar.bz2): This dataset records an undirected human contact network. The trace records all contact information and data transfer between a group of users who carry wireless devices at various locations. In the dataset, a node represents a user; an edge between two users means that there is a contact between two proximate devices.
(2) **HYCCUPS** (https://crawdad.org/upb/hyccups/20161017): This dataset is collected from trace of wireless contacts and users’ connections at the Politechnica University of Bucharest in the period from March to May 2012. 72 participants used an Android application named HYCCUPS Tracer to collect mobile interaction information in the background. It records sensor data and connectivity information between smart devices and other wireless access devices based on AllJoyn framework.
(3) **ASTURIESER** (https://crawdad.org//download/oviedo/asturies-er/asturies-er-1year-mobility.csv.gz): The dataset comprises mobility traces and connectivity information of around 229 vehicles and helicopters in the regional Fire Department of Asturias, Spain, collected over one year. Te datacenter collects devices current positions, status, contacts, etc., every 30 s. The threshold of communication distance between different devices is 10 m, 50 m or 200 m. Proximate nodes can exchange the information when the distance between them is below the threshold.
(4) **ROTAXI** (https://crawdad.org//download/roma/taxi/taxi_february.tar.gz): This dataset is derived from the real motion traces from approximately 320 taxis with GPS devices in Roma, Italy, for the duration of one month. Each taxi driver uses the location manager sofware based on GPS to retrieve longitude and latitude coordinates of current location periodically. The dataset also records time duration, speed, status, and contact information among devices.

**Comment by ajmcquilkin** [comment]
Assuming this shouldn't be on this repo
