### ISSUE TITLE
Add tooltip text to sidebar icons

### ISSUE THREAD

**Issue by ajmcquilkin** [ajmcquilkin/meshtastic-network-management-client#392]
Add tooltip text to the sidebar icons so that users can understand the icons when the sidebar is collapsed.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue.

**Comment by ajmcquilkin** [comment]
Great, thanks for your interest!

I'd probably recommend wrapping the contents of the `SidebarIcon` component with the `DefaultTooltip` component. I'm imagining you'll also want to add a prop to disable the `DefaultTooltip` component, since we won't want a tooltip when the sidebar is expanded.

**Comment by tarunsamanta2k20** [comment]
@ajmcquilkin 

![image](https://github.com/ajmcquilkin/meshtastic-network-management-client/assets/55488549/202e1289-a446-4cfb-8e21-769bbae28933)

**Comment by ajmcquilkin** [comment]
Ah hadn't considered that. Technically the client no longer supports web-only operation because we're using a native radio serial driver, but you should be okay to develop if you do the following:

1. Change line 33 in `src/App.tsx` from `const [isOnboardMounted, setOnboardMounted] = useState(true);` to `const [isOnboardMounted, setOnboardMounted] = useState(false);`
2. Don't attempt to send or receive any messages over serial. The application requires a connected Meshtastic radio to function properly, and we're bypassing this requirement since this is a UI-only ticket.

Let me know if you have trouble with that! This is a bit of a hack but should be okay for this specific ticket.

**Comment by tarunsamanta2k20** [comment]
@ajmcquilkin may I use normal react tooltip?

**Comment by ajmcquilkin** [comment]
I think I'd probably prefer you to use the existing Radix UI tooltip library in the app (already installed, [docs link](https://www.radix-ui.com/docs/primitives/components/tooltip)), but if there's a compelling reason to go with react-tooltip over Radix I'm open to discuss!

**Comment by tarunsamanta2k20** [comment]
@ajmcquilkin react-tooltip is easy to use just wrapping the tooltip tag.

**Comment by tarunsamanta2k20** [comment]
Let me check

**Comment by ajmcquilkin** [comment]
I'd recommend checking out `src/components/config/ConfigLayout.tsx` line 39, the application has a `DefaultTooltip` component that should make using the tooltip a lot simpler. Radix UI has a lot of different moving parts but `DefaultTooltip` should have a fairly similar experience to react-tooltip

**Comment by tarunsamanta2k20** [comment]
@ajmcquilkin got it. I'll use DefaultTooltip.

**Comment by ajmcquilkin** [comment]
Sounds good, feel free to reach out if you need any help!

Also for future reference I already get notified when someone comments on the issue, you don't need to tag me :)

**Comment by tarunsamanta2k20** [comment]
@ajmcquilkin I have added the default tooltip, and it's showing messages should I push?

**Comment by ajmcquilkin** [comment]
Yeah sure, feel free to create a PR on the repo! Would also be great if you could add an image in the PR of what the change ends up looking like, just for future reference
