### ISSUE TITLE
Manage Nodes location shows Latitude, Longitude as  -0.00000°,  0.00000° whilst fixed location configured for nodes

### ISSUE THREAD

**Issue by markbirss** [ajmcquilkin/meshtastic-network-management-client#419]
meshtastic-network-management-client_0.2.0_amd64.AppImage

![image](https://github.com/ajmcquilkin/meshtastic-network-management-client/assets/22388007/d7c0062d-db0a-4aff-8f2a-f7caeb016cf8)

**Comment by ajmcquilkin** [comment]
Would you mind giving some information on how you've set up your nodes? I'm setting a fixed position with the Python CLI and the position is showing up on the map.

**Comment by markbirss** [comment]
@ajmcquilkin 

Sure, i set via CLI with
`meshtastic --port /dev/ttyACM2 --set position.fixed_position true --setlat -lat --setlon lon`

They show position on map correctly it just the "Manage Node" view showing as -0.00000°, 0.00000°

**Comment by ajmcquilkin** [comment]
Ah sorry, I had misunderstood your issue. Found the bug; I had forgotten to remove something from a recent refactor. The fix is pushed to `main` and will be shipped in the next release

**Comment by markbirss** [comment]
Closed

**Comment by markbirss** [comment]
Ok to close as completed.
